url: https://clean-oryx.cloudvent.net
baseurl:
google_analytics_key:

collections:
  staff_members:
    _hide_content: true

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "default"

lab:
  university: Ohio University
  university_short: OHIO
  name: Kevin Lee Lab

newsletter_action: "//your-mailchimp-action-url.com"
