url: https://clean-oryx.cloudvent.net
baseurl:
google_analytics_key:

collections:
  staff_members:

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "default"

lab:
  university: Ohio University
  university_short: OHIO
  name: Kevin Lee Lab
  tag_line: We research diabetes
  mission_statement: The Sheep Vote is a non-profit organisation started in 2005 by the great shepard, Wooly McBaa.
  contact:
    address: 123 Example Street, City
    phone: 740-593-2327
    email: leek2@ohio.edu
    facebook:
    twitter:
    google_plus:


newsletter_action: "//your-mailchimp-action-url.com"