url: https://clean-oryx.cloudvent.net
baseurl:
google_analytics_key:

collections:
  - staff_members
  - publications

permalink: pretty

gems:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "default"

lab:
  name: Lee Lab
  tag_line: Understanding the Biology of Adipocytes
  attribution:
    university:
      name: Ohio University
      short: OHIO
      logo: /images/logos/ohio_wht.svg
      url: https://www.ohio.edu/
    college:
      name: Heritage College of Osteopathic Medicine
      short: HCOM
      logo: /images/logos/hcom.png
      url: https://www.ohio.edu/medicine/
  contact:
    address: Academic and Research Center Room 202e, Ohio University, Athens, Ohio
    phone: 740-593-2327
    email: leek2@ohio.edu
    facebook:
    twitter:
    google_plus:
  quote: Our lab seeks to uncover molecular and functional differences between morphologically indistinguishable fat cells.

form_submission:
  action: http://formspree.io/
  email: leek2@ohio.edu
form:
  background:
    placeholder: I'm a senior at ___________ studying ____________________. I'm interested in joining your lab for graduate studies. I'd like to focus research on...
